### PR TITLE
Update settings page to work on Early theme

### PR DESCRIPTION
**Pull request by Venni1**
I have updated settings page to work on Early theme, and made some logical improvements.

### CODE REVIEW

**Comment by simple-bart** [comment]
The code you provided doesn't seem to addon to the already existing code.
image
If you could, please provide some examples of your "logical improvements".

**Comment by Venni1** [comment]
Logical improvements = just the settings moved to the top of the function.
And if you test the VECTRA GO settings page on the Early theme, it doesn't work.
If you test it on my code, it works.

**Comment by simple-bart** [comment]
image
no it works

**Comment by Venni1** [comment]
on firefox it doesnt

**Comment by Venni1** [comment]
just test it on firefox

**Comment by simple-bart** [comment]
this might be a bug, could you send the console output when accessing the GO page.

**Comment by Venni1** [comment]
Uncaught (in promise) TypeError: document.querySelector(...) is null
    window["__f__lwkz7izy.bsm"]/</< moz-extension://2f140dbe-37e6-4716-b0b7-64b97dfebf6e/userscripts/VECTRA-GO.user.js?id=59af4fa4-d0a8-4860-bde2-22879a83ddf0:152
    window["__f__lwkz7izy.bsm"]/< moz-extension://2f140dbe-37e6-4716-b0b7-64b97dfebf6e/userscripts/VECTRA-GO.user.js?id=59af4fa4-d0a8-4860-bde2-22879a83ddf0:332
    wt https://www.vectra.lol/go:9
    window["__f__lwkz7izy.bsm"]/< moz-extension://2f140dbe-37e6-4716-b0b7-64b97dfebf6e/userscripts/VECTRA-GO.user.js?id=59af4fa4-d0a8-4860-bde2-22879a83ddf0:1
    "__f__lwkz7izy.bsm" moz-extension://2f140dbe-37e6-4716-b0b7-64b97dfebf6e/userscripts/VECTRA-GO.user.js?id=59af4fa4-d0a8-4860-bde2-22879a83ddf0:1
    wt https://www.vectra.lol/go:9
    o https://www.vectra.lol/go:81
    <anonymous> https://www.vectra.lol/go:84
    v https://www.vectra.lol/go:78

**Comment by simple-bart** [comment]
instead of moving the code to the early page, try to patch the bug and then i'll accept the request. the patched method seems to not do anything.

**Comment by Venni1** [comment]
if you are not gonna test it on firefox, i cant do anything. it is broken exclusively on firefox.

**Pull request closed without merging**
